/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;

import jakarta.persistence.Entity;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Authorities"
 *
 * @author Lê Chí Thiên
 *
 */

@Data
@Entity
 @NoArgsConstructor
 @AllArgsConstructor
@Table(name = "Authorities")
public class Authorities implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id 
	public String authorityid;

	@ManyToOne @JoinColumn(name = "userid")
	public Account account;

	// TODO Auto-generated method stub
	@ManyToOne  @JoinColumn(name = "roleid")
	public Roles roles;

	
	
	// public Authorities() {

	// }

	// public Authorities(String authorityid, Account account, Roles roles) {
	// 	this.authorityid = authorityid;
	// 	this.account = account;
	// 	this.roles = roles;
	// }

	public String getAuthorityid() {
		return authorityid;
	}

	public void setAuthorityid(String authorityid) {
		this.authorityid = authorityid;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Roles getRoles() {
		return roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}






		
}
