/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "Bookings"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Bookings")
public class Bookings {

    public static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    public String     bookingid ;

    //--- ENTITY DATA FIELDS 
    @Temporal(TemporalType.DATE)
    @Column(name="createat")
    public Date       createat ;

    @Column(name="cost")
    public Double     cost ;

    public String     userid ;

    public Integer    orderstatusid ;

    private Integer    shippingunitid ;
    
    @Column(name="Note")
    private String note;

	@Temporal(TemporalType.DATE)
    @Column(name="timefinish")
    public Date       timefinish ;

	public Double     costvoucher ;

	public Double     costship ;

  

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="bookings")
    @JsonIgnore
    public List<Payments> listOfPayments ; 

    @ManyToOne
    @JoinColumn(name="Orderstatusid", referencedColumnName="OrderStatusId", insertable=false, updatable=false)
    public Orderstatuses orderstatuses ; 

    @ManyToOne
    @JoinColumn(name="Userid", referencedColumnName="Userid", insertable=false, updatable=false)
    public Account    account ; 

    @OneToMany(mappedBy="bookings")
    @JsonIgnore
    public List<Detailbookings> listOfDetailbookings ; 

    @ManyToOne
    @JoinColumn(name="Shippingunitid", referencedColumnName="ShippingUnitId", insertable=false, updatable=false)
    public Shippingunits shippingunits ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(bookingid);
        sb.append("|");
        sb.append(createat);
        sb.append("|");
        sb.append(cost);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(orderstatusid);
        sb.append("|");
        sb.append(shippingunitid);
        sb.append("|");
        sb.append(note);
		sb.append("|");
        sb.append(costvoucher);
		sb.append("|");
        sb.append(costvoucher);
		sb.append("|");
        sb.append(timefinish);
        return sb.toString(); 
    }

	
	

}