/*
 * Created on 2023-10-18 ( 14:00:04 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Categories"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name = "Categories")
public class Categories implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	
	public Integer categoryid;

	// --- ENTITY DATA FIELDS
	@Column(name = "Name", length = 100)
	public String name;

	@Column(name = "Description", length = 255)	
	public String description;

	@Temporal(TemporalType.DATE)
	public Date dateadded;

	// --- ENTITY LINKS ( RELATIONSHIP )
	@OneToMany(mappedBy = "categories")
	@JsonIgnore
	public List<Typebooks> listOfTypebooks;

	// --- toString specific method
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(categoryid);
		sb.append("|");
		sb.append(name);
		sb.append("|");
		sb.append(description);
		sb.append("|");
		sb.append(dateadded);
		return sb.toString();
	}

	public Integer getCategoryid() {
		return categoryid;
	}

	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateadded() {
		return dateadded;
	}

	public void setDateadded(Date dateadded) {
		this.dateadded = dateadded;
	}

	public List<Typebooks> getListOfTypebooks() {
		return listOfTypebooks;
	}

	public void setListOfTypebooks(List<Typebooks> listOfTypebooks) {
		this.listOfTypebooks = listOfTypebooks;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}