/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.lang.StringBuilder;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Evaluates"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Evaluates")
public class Evaluates implements Serializable {

    public static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    public Integer    evaluateid ;

    //--- ENTITY DATA FIELDS 
    public String     dbid ;

    @Column(name="rating")
    public float    rating ;

    public String     reviewtext ;

    @Temporal(TemporalType.DATE)
    public Date       evaluatedate ;

    @OneToMany(mappedBy="evaluates")
    @JsonIgnore
    public List<Imageevaluates> listImageEva ; 

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="dbid", referencedColumnName="DBId", insertable=false, updatable=false)
    public Detailbookings detailbookings ; 

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder(); 
        sb.append(evaluateid);
        sb.append("|");
        sb.append(dbid);
        sb.append("|");
        sb.append(rating);
        sb.append("|");
        sb.append(reviewtext);
        sb.append("|");
        sb.append(evaluatedate);
        return sb.toString(); 
    } 

}