/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "Shippingunits"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Shippingunits")
public class Shippingunits implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    public Integer    shippingunitid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", length=50)
    public String     name ;

    public String     phonenumber ;

    @Column(name="email", length=50)
    public String     email ;

    @Column(name="address", length=100)
    public String     address ;

    public Float cod;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="shippingunits")
    @JsonIgnore
    public List<Bookings> listOfBookings ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(shippingunitid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(phonenumber);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(address);
        return sb.toString(); 
    } 

}